### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by DreierF** [ultimate-pa/javacup#1]
Hi,

is there any chance you could publish these artifacts to maven central or to a github pages maven repository here on github?

Thanks in advance

**Comment by danieldietsch** [comment]
Hi, what do you mean with _these_ artifacts? Just Javacup or something else?

**Comment by DreierF** [comment]
Thanks for the quick response!
I mean `javacup.jar` and `javacup-runtime.jar`

**Comment by danieldietsch** [comment]
@jhoenicke Lets do this this week.

**Comment by jhoenicke** [comment]
jh-javacup-1.0 is now released on oss.sonatype.org.

Feel free to reopen, if there are any problems with the release.
