### ISSUE TITLE
`.cup` file will not be parsed successfully if the package name contains `code`

### ISSUE THREAD

**Issue by chuanwise** [ultimate-pa/javacup#5]
At the beginning of `.cup` file:

```cup
package cn.chuanwise.xiaoming.message.code;
```

Java-cup will regard the word `code` as a reserved word.

**Comment by jhoenicke** [comment]
Yes, that is a bug.  I have an idea how to fix it, but I'm not sure when I will manage to make a new release.  It may take a while.

**Comment by jhoenicke** [comment]
Hmm, I just tried and it should already work. Are you using the latest version?

The `robust_id` and `symbol_id` in the grammar both have a case for CODE, so that the keyword is also regarded as a symbol.

**Comment by chuanwise** [comment]
🤔 Ummm, I just tried again, and the problem did not arise. Thank you for your help.
